### ISSUE TITLE
Seems to ignore webpack.config.js

### ISSUE THREAD

**Issue by omerts** [ColCh/jest-webpack#3]
As title suggests, it seems to ignore my webpack configuration. I am using babel-loader, but it is not working when running jest.

**Comment by omerts** [comment]
Ok, I just realized that the path to the config file needs to be added to the package.json file, with "jest-webpack-config" as the key.

Maybe should be added to docs.

**Comment by ColCh** [comment]
Sure...  I forgot about docs. Thank you for remind

**Comment by ColCh** [comment]
I've also added a link to example: e427519fd7eb6f9ccf6e45058d4aba04ae4c61b8
